FROM openjdk:17
VOLUME /tmp
EXPOSE 8080
RUN mkdir -p /app/
RUN mkdir -p /app/logs/
ADD ./build/libs/challenge-grogu-rides-0.0.1-SNAPSHOT.jar /app/challenge-grogu-rides.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=container", "-jar", "/app/challenge-grogu-rides.jar"]